### ISSUE TITLE
Conflict repo name with android_hardware_samsung

### ISSUE THREAD

**Issue by ngoquang2708** [ngoquang2708/android_hardware_sprd#3]
There is https://github.com/CyanogenMod/android_hardware_samsung repo. How would we solve this conflict? Rename our repo to android_hardware_samsung-sprd-common? Or something else?
@koquantam
@corphish

**Comment by diepquynh** [comment]
Can you explain it clearly?
Our source is different than the one in CM repo, and it's full of sprd libs instead of Exynos

**Comment by ngoquang2708** [comment]
Our sprd-common folder is inside samsung folder!

**Comment by corphish** [comment]
Maybe we could use like `android_hardware_sprd`
You see, there are tonnes of qcom devices in CM git, and many different OEMs manufacture them, not one.
So there is nothing like `android_hardware_<put your oem here>_qcom_<module name>`.
Its done like this:
`android_hardware_qcom_<module>`
Example:
`android_hardware_qcom_display`
`android_hardware_qcom_audio`
and so on..
It will be a pain for us to maintain different repos for different modules, so best way I see is to maintain  **1 single** repo in hardware/sprd/`module name`/`board`
Example:
hardware/sprd/audio/sc8830
hardware/sprd/camera/sc8810

**Comment by diepquynh** [comment]
Yeah I was about to say like @corphish
Btw, seems that idea is nice. Do you agree? @ngoquang2708

**Comment by ngoquang2708** [comment]
OK. That nice. So what we need to do? Just change the repo name, then change the hardware/samsung/sprd-common to hardware/sprd in Makefiles or else what I am missing?

**Comment by diepquynh** [comment]
For makefiles you have already got LOCAL_PATH yeah?
So just change folder name

**Comment by ngoquang2708** [comment]
Some Makefiles use hard-coded path so we will need to change them too.

2016-08-09 22:50 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by ngoquang2708** [comment]
Renamed.
